site_name: CS101

theme: readthedocs

plugins:
  - search
  #- markdownextradata: {}

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/projects.md
      - Hangman: projects/hangman/hangman.md
