site_name: Computer Science 101

theme:
  name: material
  palette:
    primary: blue grey

  logo: 'img/logo.png'


plugins:
  - search
  #- markdownextradata: {}

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/projects.md
      - 1. Hangman:
            Instrucciones: projects/hangman/hangman.md
            Para Entregar: projects/hangman/para_entregar.md
