site_name: Computer Science 101

repo_url: https://github.com/cs-ufm/cs101-2020

theme:
  name: material
  palette:
    primary: blue grey

  logo: 'img/logo.png'


plugins:
  - search
  #- markdownextradata: {}
markdown_extensions:
  - codehilite
  - footnotes
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/projects.md
      - 1. Hangman:
            1. Instrucciones: projects/hangman/hangman.md
            2. Forma de Entrega: projects/hangman/para_entregar.md
